[package]
name = "coastguard"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
time = "*"
[dependencies.hyper]
version = "0.6"
features = ["timeouts"]